### ISSUE TITLE
GPU memory consumption is high

### ISSUE THREAD

**Issue by minrui-hust** [yichen928/SparseFusion#11]
Can not finish training with 3090(24GB) even set batch_size to 1, any advise?

**Comment by yichen928** [comment]
Hi! Thanks for your interest. 
You can simply reduce the GPU memory without any damage to performance by editing the `generate_heatmap_deform` function in `mmdet3d/models/dense_heads/sparsefusion_head_deform.py`. The following part can run on each view separately in a for-loop.

https://github.com/yichen928/SparseFusion/blob/89a7c5a9e2a1bd1bf63631819af8a78c69df744c/mmdet3d/models/dense_heads/sparsefusion_head_deform.py#L705

In this case, you do not need to pad the input queries as in https://github.com/yichen928/SparseFusion/blob/89a7c5a9e2a1bd1bf63631819af8a78c69df744c/mmdet3d/models/dense_heads/sparsefusion_head_deform.py#L671

This would not harm the performance but may very slightly slow down the inference, so you can also only modify this during training. We will also update a version with this change soon.

**Comment by minrui-hust** [comment]
Thanks for your advise, I'll try it. 
BTW ,would you provide your training logs for reference, currently, only ckpt and config is available

**Comment by yichen928** [comment]
This is a log file of our training (ResNet50 backbone) [20230717_235818.log](https://github.com/yichen928/SparseFusion/files/12257281/20230717_235818.log). Please notice that this is a different training with our provided checkpoint, so the final performance is slightly different.

**Comment by BoomSky0416** [comment]
@yichen928 Hello, I have two question about this change for gpu memory reduce. Is it necessary to set up multiple cross_heatmap_decoders for each view? And how to only modify this during training, what's the difference between training and inference?

**Comment by SISTMrL** [comment]
> 
yichen，你好，很抱歉看了你的回答后，还是不清楚该怎么修改代码，是在做cross attn的时候，执行红框部分的代码吗
![image](https://github.com/yichen928/SparseFusion/assets/47938053/7a174e82-d8a5-412a-afef-1b2ee36de72c)

**Comment by yichen928** [comment]
> > 
> 
> yichen，你好，很抱歉看了你的回答后，还是不清楚该怎么修改代码，是在做cross attn的时候，执行红框部分的代码吗？ 另外改完后，可以直接resume吗，模型参数会不会改，我训到第三个epoch，显存爆了 ![image](https://user-images.githubusercontent.com/47938053/260608860-7a174e82-d8a5-412a-afef-1b2ee36de72c.png)

I have updated a new version of the code with much better GPU efficiency. It would be helpful and more identifiable to re-open the issue when you have any following questions.
