### ISSUE TITLE
Semantic information transfer

### ISSUE THREAD

**Issue by zhaowenZhou** [yichen928/SparseFusion#12]
I'm wondering in which step was the semantic information fusion done? It seems like it was done in HardVFE but in your README file, the model is sparsefusion_nusc_voxel_LC_r50.py which used HARDSimpleVFE, it doesnt contain semantic information fusion

**Comment by yichen928** [comment]
Hi. Thanks for your interest. The semantic information transfer is done in `mmdet3d/models/dense_heads/sparsefusion_head_deform.py` https://github.com/yichen928/SparseFusion/blob/89a7c5a9e2a1bd1bf63631819af8a78c69df744c/mmdet3d/models/dense_heads/sparsefusion_head_deform.py#L598
