### ISSUE TITLE
pretrain config

### ISSUE THREAD

**Issue by BoomSky0416** [yichen928/SparseFusion#13]
Could you provide the config for lidar pretrain? Thanks!
I noticed the pre-trained ckpt have been provided. But I want to reproduce the whole training process.

**Comment by yichen928** [comment]
It is same with [TransFusion-L](https://github.com/XuyangBai/TransFusion/blob/master/configs/transfusion_nusc_voxel_L.py). You can directly use their codebase. Also, you need to rename the parameters in the `shared_conv` layer (https://github.com/fudan-zvg/DeepInteraction/issues/17).
