### ISSUE TITLE
extract_voxel_heights

### ISSUE THREAD

**Issue by SISTMrL** [yichen928/SparseFusion#16]
你好，能解释下extract_voxel_heights的含义是啥吗，看了后有点懵，谢谢
![image](https://github.com/yichen928/SparseFusion/assets/47938053/85bd08c2-3f3e-4d23-ba0e-7aab13ebc184)

**Comment by yichen928** [comment]
BEV feature map大小是N*N，这个函数就是计算这N*N个网格每个格子里点云的最大和最小高度，方便后面把semantic transfer中把LiDAR branch的BEV feature和camera branch的image feature对应起来。

**Comment by SISTMrL** [comment]
谢谢！！！
