### ISSUE TITLE
About the LiDAR branch 

### ISSUE THREAD

**Issue by qzhang852** [yichen928/SparseFusion#18]
Dear author,
Thank you for your excellent work. I wonder how do you get LiDAR branch with semantic transfer, add the 
```
sample_query_feature = sample_query_feature + sample_query_img_feat
``` 
directly in the ```transfusion_nusc_voxel_L.py``` ? 
Thank you for taking the time.

**Comment by yichen928** [comment]
Thanks for your interest. This line is in the semantic transfer module. This module gives a better initial query position for the LiDAR branch, but the initial query features of LiDAR branch still come from only the LiDAR branch. In this case, we can directly re-use the architecture and pretrained weight of transfusion-L without any modifications.
