### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by bringBackm** [yichen928/SparseFusion#19]
change freeze_lidar_components=False, will report following error

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 6, 32400, 1]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 207483) of binary:

**Comment by yichen928** [comment]
Thanks for your interest! If you want to finetune the LiDAR backbone, please also delete the following code: https://github.com/yichen928/SparseFusion/blob/e5e2af2903c8f60ff6fd1e0cc779443bd4daf02d/tools/train.py#L184-L185

and 

https://github.com/yichen928/SparseFusion/blob/e5e2af2903c8f60ff6fd1e0cc779443bd4daf02d/tools/train.py#L203-L207

From my experience, finetuning the LiDAR branch or even the LiDAR backbone would not lead to notable performance gain.

**Comment by bringBackm** [comment]
Thanks
