### ISSUE TITLE
The problem with FPS during inferencing

### ISSUE THREAD

**Issue by liyih** [yichen928/SparseFusion#24]
Hi, yichen,
Thanks for your awesome work. I use A100 to inference your Resnet-50 based model, and only get FPS=2.1. It's strange, as in your table 4, you got FPS=5.6 with A6000. I use tools/analysis_tools/benchmark.py for inference. I want to know how do you calculate the FPS in your model.
Best

**Comment by liyih** [comment]
I guess you don't consider voxelization time just as bevfusion(MIT) do. I remove the voxelization time and got fps=6.4 in A100, that looks good.

**Comment by yichen928** [comment]
> I guess you don't consider voxelization time just as bevfusion(MIT) do. I remove the voxelization time and got fps=6.4 in A100, that looks good.

That is correct! Thanks for your interest.
