### ISSUE TITLE
关于combie_view_info.py中的偏航角

### ISSUE THREAD

**Issue by jiumozhi123** [yichen928/SparseFusion#27]
熠辰您好，非常感谢您的这份工作，它非常有价值！
在研究预处理代码的过程中，我有一点问题想咨询一下您
![截图 2024-02-17 02-38-14](https://github.com/yichen928/SparseFusion/assets/8881222/8d0a05b1-d9d6-4620-8246-74d5cfa502c7)

关于这个yaw，它经过了两次取负减90度角的处理，现在应该是**自车坐标系**(x轴向前，y轴向左)的偏航角(逆时针)是吗？
然后我猜想您的意思是想在(激光)雷达坐标系中得到每个gt_box的朝向向量，再转换到相机坐标系中
如果yaw是**雷达坐标系**x轴向左的偏航角，那么这个操作没有任何问题，cos(yaw)对应x方向，sin(yaw)对应y方向，然后转换到相机坐标系
但是雷达坐标系(x轴向右，y轴向前)和自车坐标系还是不一样的，差了90度角
这里您再确认一下是不是有点问题？

**Comment by jiumozhi123** [comment]
非常感谢您的工作，只是想确认下这个小问题

**Comment by yichen928** [comment]
感谢您的兴趣。combie_view_info.py中第124行处是将方向角由自车坐标系转换到雷达坐标系，131行处将方向向量由雷达坐标系转换到相机坐标系，140行处在相机坐标系中将方向向量转换成方向角（mmdet3d相机坐标系中方向角定义参照mmdet3d/core/bbox/structures/cam_box3d.py中注释）。

**Comment by jiumozhi123** [comment]
好的，非常感谢！！！！

**Comment by yichen928** [comment]
> 好的，非常感谢！！！！ 131行处将方向向量由雷达坐标系转换到相机坐标系 ———这里应该是137行吧

对应该是137行
