### ISSUE TITLE
关于lidar2img参数

### ISSUE THREAD

**Issue by jiumozhi123** [yichen928/SparseFusion#29]
熠辰您好，最近阅读SparseFusion代码的**训练时数据增强**部分，有一个小疑问：

由于在SparseFusion的体系里，包含雷达坐标系(LiDARInstance3DBoxes)，相机坐标系(CameraInstance3DBoxes)，图像坐标系
所以每次在对3D或2D图像\真值做增强的时候，基本都要对以下映射参数如：
雷达到相机(lidar2cam_r, lidar2cam_t)，相机到图像(cam_intrinsic)进行相应的调整，保证雷达空间、相机空间、图像空间映射的一致性

然而雷达到图像(lidar2img)这个参数似乎例外，仅仅在OurRandomAffine里做了对应的变换，其他步骤里都没有做。想问下您这样做的考虑是什么呢？
希望能够得到您的解答

**Comment by yichen928** [comment]
你好，感谢你的兴趣。

我们在OurGlobalRotScaleTrans和OurRandomFlip3D同样对lidar2img参数进行了对应的变换，而不仅仅是OurRandomAffine。
