### ISSUE TITLE
Robustness Study

### ISSUE THREAD

**Issue by TillBeemelmanns** [yichen928/SparseFusion#33]
Hi,

thanks for this interesting work! I did a small robustness study on multi-modal object detectors and found out, that SparseFusion performs quite well on a diverse set of corruptions. Maybe you are interested in this.

Code: https://github.com/ika-rwth-aachen/MultiCorrupt
Preprint: https://arxiv.org/abs/2402.11677

Our results will be published in the IEEE Intelligent Vehicles Symposium, June 2024.

Thanks!

Bests,
Till

**Comment by yichen928** [comment]
Hi Till, 

Thanks very much for your interesting exploration! I believe robustness is a very important point for 3D perception. I will definitely read your paper carefully.

Best,
Yichen
