### ISSUE TITLE
Question about mmdetection3D install.

### ISSUE THREAD

**Issue by sidiangongyuan** [yichen928/SparseFusion#35]
I have trouble in installing mmdet3D package. 

![image](https://github.com/yichen928/SparseFusion/assets/74222548/0dc944b4-cf61-4a73-90c4-d93f3f8d9c3a)

Here is my version . 

All other packages is installed well except mmdet3d.  

when I use pip install -e .   
![image](https://github.com/yichen928/SparseFusion/assets/74222548/4eaef6a5-c991-470c-83de-37a5140a828f)

**Comment by yichen928** [comment]
You may scroll up the terminal, and there should exist the concrete error message.

**Comment by Ge-huihui** [comment]
你好，你这个问题解决出来了吗   我现在也遇到了和你一样的问题
