### ISSUE TITLE
Support no query or no query pos

### ISSUE THREAD

**Issue by frkmac3** [yichen928/SparseFusion#36]
https://github.com/yichen928/SparseFusion/blob/b1b14e91c11a769b15f30bdf0b47ef9146b1030e/mmdet3d/models/dense_heads/sparsefusion_head_deform.py#L727
https://github.com/yichen928/SparseFusion/blob/b1b14e91c11a769b15f30bdf0b47ef9146b1030e/mmdet3d/models/utils/deformable_decoder.py#L71
If no object is found, both `query` and `query_pos` can be None, which may result in an error here.

**Comment by yichen928** [comment]
I think our method would always detect a fixed number of objects from the LiDAR and images. If there is actually no object, the detection confidence would be very low.
