### ISSUE TITLE
关于对nuscenes_mini数据集预处理

### ISSUE THREAD

**Issue by ZhangYK618** [yichen928/SparseFusion#38]
熠辰您好！当我尝试使用“python tools/create_data.py nuscenes --root-path ./data/nuscenes_mini --out-dir ./data/nuscenes_mini --extra-tag nuscenes --version v1.0-mini”来预处理nuscenes_mini数据集的时候在“Create GT Database of NuScenesDataset“时出现了” TypeError: expected dtype object, got 'numpy.dtype[bool_]' “的错误，正如下面的截图所示。我在网上了解到这可能是由于numpy和numba版本的问题，但是我并没有成功的解决这个问题。
请问您在处理的时候有没有碰到过这个问题，您是如何解决的。或者我想使用nuscenes mini数据集的话应该用什么命令处理数据集呢？

**Comment by yichen928** [comment]
请参考这个问题：https://github.com/yichen928/SparseFusion/issues/23

**Comment by ZhangYK618** [comment]
> 请参考这个问题：#23 应该是numpy和numba的版本问题，与mini无关

谢谢熠辰！我重新配置了一个conda环境之后解决了这个问题
