### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Dragonzz27** [yichen928/SparseFusion#42]
I apologize for taking up your time.

I want to reproduce the experiments in this paper.

I would like to know the hardware configuration of the servers used in the experiment, the number of GPUs used, and the training time for each experiments of the model.

**Comment by yichen928** [comment]
Thanks for your interest. It requires about two days to train our model on nuScenes full training set with 4 A6000 GPUs for both ResNet50 and Swin-T backbone based on the pretrained TransFusion-L checkpoints.

**Comment by Dragonzz27** [comment]
Yes for your answer, I will have a trial to run the experiments with 4 4090.
