### ISSUE TITLE
关于创建数据的问题

### ISSUE THREAD

**Issue by Ge-huihui** [yichen928/SparseFusion#44]
请问作者，就是这种她目录下存在   但是他报错说不存在这一块   这是啥原因啊  ，这该怎么解决啊   我在我在tools下建立了一个空的__init__.py文件    他还是不行
![3060882d3df6a63d35761eff0f06ca7](https://github.com/user-attachments/assets/f38835c1-a318-4f23-8d19-0e0b164aef3d)

**Comment by yichen928** [comment]
一般应该不会有这个问题，如果出现的话可以考虑把SparseFusion根目录加到sys.path里面
