### ISSUE TITLE
test集的结果

### ISSUE THREAD

**Issue by spiderforest** [yichen928/SparseFusion#45]
你好，我在复现SparseFusion结果时遇到了一些问题：
我按照github提供的步骤安装了pytorch环境，并按照指令处理了数据集。使用good driver提供的已训练好权重可以在val集上跑出论文中的结果(70.5,72.8)，但在test集中只能得到下面的结果，请问生成测试集json文件时还需要其他额外的设置吗？以下是我的生成json的命令和eval评估的结果。
bash tools/dist_test.sh ${config} ${checkpoint} 1 --options jsonfile_prefix=${dir}  --format-only

![image](https://github.com/user-attachments/assets/8c2a73f6-b93a-4611-b4e4-a70afa3ed1b9)

**Comment by Ge-huihui** [comment]
![5e9c659afaaefd3f1bbc6deaddb3072](https://github.com/user-attachments/assets/77fce3ee-1f3a-42bd-93b1-24716616f471)
您好，想请教一下您，我的环境全是按照作者readme里面说明的进行配置的，但是一进行跑训练的时候，出现这个错误是为什么啊。或者能请教一下您，您的环境情况嘛

**Comment by Ge-huihui** [comment]
![96d244b3429c1a64295fb63aa83c7a0](https://github.com/user-attachments/assets/a4fd3676-d7f7-47a7-ad57-14680d7df27b)
您好，想请教一下您，我的环境全是按照作者readme里面说明的进行配置的，但是一进行跑训练的时候，出现这个错误是为什么啊。或者能请教一下您，您的环境情况嘛
