### ISSUE TITLE
关于mmcv相关的问题

### ISSUE THREAD

**Issue by Ge-huihui** [yichen928/SparseFusion#46]
您好，作者 。目前我的环境是这样的  python=3.8.27      cuda=11.3   pytorch、torchvision、torchaudio是按照链接conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=11.3 -c pytorch -c conda-forge   numba=0.48.0   numpy=1.19.5  mmdet=3.3.0  mmcv=2.0.0rc4   mmcv-full=1.3.16       但是再运行训练语句的时候，出现错误
![7b4025952d1e9f679dd2d518fafb62a](https://github.com/user-attachments/assets/8754c84f-6ae4-40b9-9b5a-b10fd7caee30)
xiang想问一下，这个粗哦呜我该怎么办啊

**Comment by yichen928** [comment]
请参考mmcv对应版本官方文档安装mmcv-full，之后不再需要额外安装mmcv
