### ISSUE TITLE
Sparse depth generation

### ISSUE THREAD

**Issue by BoomSky0416** [yichen928/SparseFusion#6]
I found you only use point from the first timestamp to generate sparse depth, is it too sparse? Have you tried to use all points to generate depth map?

**Comment by yichen928** [comment]
Since the resolution of feature maps are downsampled, the depth map would not be too sparse. We tried to use point clouds from all sweeps, which led to a slightly worse performance due to object motion.

**Comment by BoomSky0416** [comment]
Thank you for your speedy response.
