### ISSUE TITLE
gpu-memory  keep  increasing  after 2nd iteration

### ISSUE THREAD

**Issue by cbyAIybh** [yichen928/SparseFusion#7]
hi, i encountered an issue when i run train scipt.  Test result is ok and the same as shown in readme.  
But the gpu-memory keeps increasing after 2nd iteration  when getting into  DeformableTransformerDecoderLayer(MutliHeadAttention  and MSDeformAtten).  The max_gpu_reserved can reach even more than 80G.

The environment is as follows(for some reasons, config and envs list are not allowed to paste out of inside network, sorry):
Ubuntu，pytorch1.10, cuda11.1, mmdet3d(same as readme)。
Nuscenes full1.0 and mini dataset are used to train as test.
config is the official  sparsefusion_nusc_voxel_LC_r50.py.

Look forward to your reply!

**Comment by yichen928** [comment]
In our training process, the GPU memory may fluctuate, but it is always within the range of A6000 GPUs (48GB). In your training process, (1) does the memory overflow always happen after the 2nd iteration? (2) We use DeformableTransformerDecoderLayer multiple times in the pts_bbox_head. Can you find which time cases this problem?

**Comment by cbyAIybh** [comment]
@yichen928 Thanks for your reply.  in my opinion, after the 2nd iteration, the tensor cache of gpu memory should be stable(even if a little fluctuation). The memory increasing in my clone project occurs in MutliHeadAttention and MSDeformAtten forward function sometimes, and the deep condition of this phenomenon has not been found.

(1) this is debug process of gpu memory allocated and cached with torch.cuda.max_memory_allocated and cached.In this porcess, non-zereo value of allocated and cached are shown.
![debug process](https://github.com/cbyAIybh/imgs/blob/main/WechatIMG68.jpg)

(2) the following img shows the exact position which generate non-zero value of increasing memory.
>transformerdecoder.py
``` python
if key_padding_mask is not None:
   ...
    attn_output_weights = attn_output_weights.masked_fill(
        key_padding_mask.unsqueeze(1).unsqueeze(2), 
        float('inf'),
    )
    attn_output_weights = attn_output_weights.view(bsz * num_heads, tgt_len, src_len)
```
![exact position](https://github.com/cbyAIybh/imgs/blob/main/WechatIMG68.jpg)

i am not famialier with DeformableTransformer. May the bug be related to pytorch version(v1.10 vs. 1.7.1)? or dcn_v2 package(at the begining of train process, "import DCN failed" message is printed)?

**Comment by yichen928** [comment]
I tried the training code again, and it can still run within 40G memory on my A6000 GPUs. From my experience, if you are using A100 GPUs, it would need more memory (but I do not know why), so it may not fit in the 40G memory of A100. You may try to half the batch size to see whether it still overflows.
I did not try with our pytorch version, but you can try to use 1.7.1 same as me. The DCN is not actually used, you can just ignore the "import DCN failed" message.

**Comment by yichen928** [comment]
Another suggestion is to limit the max power of your GPU with "nvidia-smi -pl 200" (200 is the limitation). This would not slow down your training, but can indeed save a lot of memory.

**Comment by cbyAIybh** [comment]
The environment with torch-1.7.1 seems to work well, even if a little fluctuation exists.  
However, the env with pytorch1.10 still overflows. But there is no evidence to suggest that torch.masked_fill can cause the overflow.

**Comment by yichen928** [comment]
glad to know that! We will dig into this problem further.
