### ISSUE TITLE
AttributeError: 'DataContainer' object has no attribute 'shape'

### ISSUE THREAD

**Issue by BoomSky0416** [yichen928/SparseFusion#8]
I encounter this error during inference. Here is my env.
![image](https://github.com/yichen928/SparseFusion/assets/57380777/7f8b2a51-371b-4bd9-bee6-570de60beb72)

**Comment by yichen928** [comment]
Hi Thanks for your interest. I did not encounter this error. Can you share more details such as the error message or the concrete line causing this error?

**Comment by BoomSky0416** [comment]
Thanks for your response. Here is the screenshot of the error message.
![image](https://github.com/yichen928/SparseFusion/assets/57380777/1a1df39f-bbbf-478e-b5ba-024815367b1e)

**Comment by yichen928** [comment]
Can you check that 1) Are you using PyTorch 1.7 now? 2) Are your GPUs available by checking `torch.cuda.is_available()`?

**Comment by BoomSky0416** [comment]
Oh, my Pytorch version is 1.9.0

**Comment by yichen928** [comment]
Please consider re-installing your environment with PyTorch 1.7
