### ISSUE TITLE
install he mmdet==2.10.0

### ISSUE THREAD

**Issue by SISTMrL** [yichen928/SparseFusion#9]
你好，机器的cuda版本是11.7
安装torch的指令是：pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html
安装mmcv-full的指令是：pip install mmcv-full==1.2.7 -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.7.1/index.html
numpy==1.20.0
numba==0.48.0

但是执行pip install mmdet==2.10.0，出现fail to build mmpycocotools，请问下该如何解决呢？(;´༎ຶД༎ຶ`) 谢谢！
<img width="499" alt="1690786052325" src="https://github.com/yichen928/SparseFusion/assets/47938053/f08dd6e7-595a-4114-96b1-7a495fe0b77c">

**Comment by SISTMrL** [comment]
我下载了mmdetection 2.10.0的源码进行编译，还是出现fail to build mmpycocotools(;´༎ຶД༎ຶ`)

**Comment by SISTMrL** [comment]
最新的mmdet不需要mmpycocotools，但是装上后，mmcv的版本就不能用了

**Comment by yichen928** [comment]
I think you may try to install mmpycocotools manually by running the following code:
`pip uninstall pycocotools`
`pip uninstall mmpycocotools`
`pip install mmpycocotools`

**Comment by SISTMrL** [comment]
> I think you may try to install mmpycocotools manually by running the following code: `pip uninstall pycocotools` `pip uninstall mmpycocotools` `pip install mmpycocotools`

hi, it doesn't work, do you have any ideas?

**Comment by yichen928** [comment]
https://github.com/cocodataset/cocoapi/issues/172
Maybe this issue can help.

**Comment by SISTMrL** [comment]
> [cocodataset/cocoapi#172](https://github.com/cocodataset/cocoapi/issues/172) Maybe this issue can help.

thanks, i will have a try

**Comment by SISTMrL** [comment]
> [cocodataset/cocoapi#172](https://github.com/cocodataset/cocoapi/issues/172) Maybe this issue can help.

thank you, i found the correct way to install mmdet in the link you provided. Just use conda to install cython, not pip
